#! /usr/bin/env perl

use strict;
use warnings;
use 5.010;

# PODNAME: xt/author/unused-vars.t

# ABSTRACT: All variables in modules are actually used?

our $VERSION = '0.0.2'; # VERSION

#pod =head1 SYNOPSIS
#pod
#pod     # Run just this author test
#pod     # cd <some built distribution version directory>
#pod     prove -lr xt/author/unused-vars.t
#pod
#pod     # Run all author tests
#pod     # cd <developer distribution directory>
#pod     dzil test # [RunExtraTests] dist.ini plugin runs author tests by default.
#pod
#pod =head1 DESCRIPTION
#pod
#pod Unused variables are at best a waste of memory but may represent an error due to
#pod a misspelling. Actual errors are likely caught elsewhere though.
#pod
#pod Based on the test auto-generated by
#pod L<Dist::Zilla::Plugin::Test::UnusedVars|Dist::Zilla::Plugin::Test::UnusedVars>.
#pod Essentially just a wrapper around
#pod L<Test::Vars::all_vars_ok()|Test::Vars/all_vars_ok(%args)>.
#pod
#pod This is similar to the
#pod L<Perl::Critic::Policy::Variables::ProhibitUnusedVariables|Perl::Critic::Policy::Variables::ProhibitUnusedVariables>
#pod but uses a different approach. It scans the compiled source rather than a simple
#pod source inspection scan. That is likely more comprehensive and more correct, but
#pod it is also probably more expensive. The L<Perl::Critic|Perl::Critic> policy is
#pod still needed, that can also be applied to executable and test files, this can
#pod not.
#pod
#pod This is an author test as failure is a code quality issue.
#pod
#pod Does not test variables in scripts or tests.
#pod
#pod =cut

use Test::More 0.96 tests => 1;    # Test harness, running one test

my $isFound = eval {
   require Test::Vars;             # Implements test for unsued vars
   1;
};

#pod =head1 TESTS
#pod
#pod =head2 calling Test::Vars::all_vars_ok()
#pod
#pod Checks all variables in a distribution's modules. That means the files in the
#pod MANIFEST with names like "lib/*.pm". This is true even on windows, as the
#pod manifest always uses a fixed "/" directory separator - see
#pod L<ExtUtils::Manifest|ExtUtils::Manifest>.
#pod
#pod =cut

SKIP: {
   if ( ! $isFound ) {
      skip( 'Test::Vars required for testing for unused vars', 1 );
   }

   Test::Vars->import();

   subtest(
      'All vars used?' => sub {
         all_vars_ok();
      }
   );
}

__END__

=pod

=encoding UTF-8

=for :stopwords Stuart R. Jefferys

=head1 NAME

xt/author/unused-vars.t - All variables in modules are actually used?

=head1 VERSION

version 0.0.2

=head1 SYNOPSIS

    # Run just this author test
    # cd <some built distribution version directory>
    prove -lr xt/author/unused-vars.t

    # Run all author tests
    # cd <developer distribution directory>
    dzil test # [RunExtraTests] dist.ini plugin runs author tests by default.

=head1 DESCRIPTION

Unused variables are at best a waste of memory but may represent an error due to
a misspelling. Actual errors are likely caught elsewhere though.

Based on the test auto-generated by
L<Dist::Zilla::Plugin::Test::UnusedVars|Dist::Zilla::Plugin::Test::UnusedVars>.
Essentially just a wrapper around
L<Test::Vars::all_vars_ok()|Test::Vars/all_vars_ok(%args)>.

This is similar to the
L<Perl::Critic::Policy::Variables::ProhibitUnusedVariables|Perl::Critic::Policy::Variables::ProhibitUnusedVariables>
but uses a different approach. It scans the compiled source rather than a simple
source inspection scan. That is likely more comprehensive and more correct, but
it is also probably more expensive. The L<Perl::Critic|Perl::Critic> policy is
still needed, that can also be applied to executable and test files, this can
not.

This is an author test as failure is a code quality issue.

Does not test variables in scripts or tests.

=head1 TESTS

=head2 calling Test::Vars::all_vars_ok()

Checks all variables in a distribution's modules. That means the files in the
MANIFEST with names like "lib/*.pm". This is true even on windows, as the
manifest always uses a fixed "/" directory separator - see
L<ExtUtils::Manifest|ExtUtils::Manifest>.

=cut
